### ISSUE TITLE
python gitlabservicehook.py install error  File "gitlabservicehook.py", line 14

### ISSUE THREAD

**Issue by thetuxinator** [alexgit2k/trac-gitlab-service-hook#2]
python gitlabservicehook.py install gives an error:

Traceback (most recent call last):
  File "gitlabservicehook.py", line 14, in <module>
    from trac.ticket.notification import TicketNotifyEmail
ImportError: cannot import name TicketNotifyEmail

regards

MIke

**Comment by thetuxinator** [comment]
Could be the same as https://trac.edgewall.org/ticket/3216, will try this

**Comment by thetuxinator** [comment]
Seems that the actual function TicketNotifyEmail has been deprecated and replaced  see https://trac.edgewall.org/changeset/13578

**Comment by thetuxinator** [comment]
@mwaeckerlin could you maybe help here?

**Comment by alexgit2k** [comment]
Which Trac-version are you using?

The plugin has been developed for Trac 1.0.x.

**Comment by thetuxinator** [comment]
Hi, we recently upgraded to Trac 1.2.x as 1.0 is "oldstable"

**Comment by alexgit2k** [comment]
We are stuck to 1.0 as another plugin is only working with 1.0. So there are no plans yet to upgrade this plugin to Trac 1.2 or newer.

**Comment by thetuxinator** [comment]
Are you refering to Notifymail or which other plugin?

**Comment by alexgit2k** [comment]
Agilo for Trac (https://trac-hacks.org/wiki/AgiloForTracPlugin)

**Comment by thetuxinator** [comment]
Hmm, i see no code reference to AgiloForTracPlugin and in your install instructions it is not mentioned. Do i misunderstand?

**Comment by alexgit2k** [comment]
Correct, AgiloForTracPlugin has nothing to do with Gitlab-Service-Hook. Agilo for Trac is one of other plugins used independently of Gitlab-Service-Hook here, but requires Trac 1.0.
